# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 589f8ec4c77728d2ba92c4d684558233babd3b0f114acbc082b5d2abe76977efa56e390a42fd4cb0ddd7789f6b74ffe0ea42d0699d6e339959597f02de5d2615

test:
  secret_key_base: 9cec02c96c6e71e5379a61092c1b44ea8f08de91f74a622307f01f3cfed45822c61c2f4ed7fcf9e86983b1a73f1b8d7175e392eaa6d1523cbaecaef8057cec30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
